"""Build the coverage matrix: (table, symbol, venue, date) -> rows / span / bytes.

Walks the parquet tree, summarizes each partition (via DuckDB so it's fast), writes
the result to:
  - the `coverage` DuckDB metadata table,
  - `data/meta/coverage.json`     (machine-readable),
  - `data/meta/coverage.md`       (a human-readable matrix you can paste into a doc).

Usage:
    python -m scripts.coverage_report
"""
from __future__ import annotations

import json
import logging
import sys
import time
from collections import defaultdict

import pandas as pd

from cryptodata.paths import DERIVED_ROOT, META_ROOT, RAW_ROOT, ensure_dirs
from cryptodata.storage.duckdb_views import connect
from cryptodata.storage.schemas import SCHEMAS

log = logging.getLogger("coverage_report")

_TS_TABLES = {  # tables whose rows carry a ts_ns we can summarize
    "trades", "quotes", "funding", "open_interest", "book_l2_snapshot", "bars_1s", "bars_ref",
}


def _partition_bytes(table: str, symbol: str, venue: str, date: str) -> int:
    root = DERIVED_ROOT if table.startswith("bars") else RAW_ROOT
    part = root / table / f"symbol={symbol}" / f"venue={venue}" / f"date={date}"
    if not part.exists():
        return 0
    return sum(f.stat().st_size for f in part.glob("*.parquet"))


def build_coverage() -> pd.DataFrame:
    ensure_dirs()
    now_ns = time.time_ns()
    rows: list[dict] = []
    with connect() as con:
        for table in SCHEMAS:
            if table not in _TS_TABLES:
                continue
            try:
                # .fetchall() (not fetchdf) so the hive `date` partition column comes back
                # as a clean YYYY-MM-DD via str(), not a pandas Timestamp with a time part.
                grp = con.execute(
                    f"SELECT symbol, venue, CAST(date AS VARCHAR) AS d, COUNT(*) AS n, "
                    f"MIN(ts_ns) AS lo, MAX(ts_ns) AS hi "
                    f"FROM {table} GROUP BY symbol, venue, date ORDER BY symbol, venue, date"
                ).fetchall()
            except Exception:
                continue
            for symbol, venue, date, n, lo, hi in grp:
                date = str(date)[:10]
                lo, hi = int(lo), int(hi)
                rows.append({
                    "table_name": table, "symbol": symbol, "venue": venue, "date": date,
                    "rows": int(n), "first_ts_ns": lo, "last_ts_ns": hi,
                    "span_seconds": int((hi - lo) // 1_000_000_000),
                    "bytes_on_disk": _partition_bytes(table, symbol, venue, date),
                    "computed_at_ns": now_ns,
                })
    df = pd.DataFrame(rows)
    if df.empty:
        log.warning("coverage: no parquet data found")
        return df

    with connect() as con:
        con.execute("DELETE FROM coverage")
        con.executemany(
            """INSERT INTO coverage
               (table_name, symbol, venue, date, rows, first_ts_ns, last_ts_ns, span_seconds, bytes_on_disk, computed_at_ns)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            [(r.table_name, r.symbol, r.venue, r.date, int(r.rows), int(r.first_ts_ns), int(r.last_ts_ns),
              int(r.span_seconds), int(r.bytes_on_disk), int(r.computed_at_ns)) for r in df.itertuples(index=False)],
        )
    return df


def _summary(df: pd.DataFrame) -> dict:
    if df.empty:
        return {"partitions": 0}
    by_table = df.groupby("table_name").agg(
        partitions=("rows", "size"), rows=("rows", "sum"), bytes=("bytes_on_disk", "sum"),
        symbols=("symbol", "nunique"), venues=("venue", "nunique"),
        first_date=("date", "min"), last_date=("date", "max"),
    ).reset_index()
    return {
        "partitions": int(df.shape[0]),
        "total_rows": int(df["rows"].sum()),
        "total_bytes": int(df["bytes_on_disk"].sum()),
        "symbols": sorted(df["symbol"].unique().tolist()),
        "venues": sorted(df["venue"].unique().tolist()),
        "dates": sorted(df["date"].unique().tolist()),
        "by_table": by_table.to_dict("records"),
        "computed_at_ns": time.time_ns(),
    }


def _markdown_matrix(df: pd.DataFrame) -> str:
    out = ["# Coverage matrix", "", "Generated by `cda-coverage`. Rows = parquet record counts.", ""]
    for table in sorted(df["table_name"].unique()):
        sub = df[df["table_name"] == table]
        symbols = sorted(sub["symbol"].unique())
        venues = sorted(sub["venue"].unique())
        out.append(f"## `{table}`  — {int(sub['rows'].sum()):,} rows, "
                   f"{int(sub['bytes_on_disk'].sum())/1024/1024:.2f} MB, "
                   f"{sub['date'].min()}..{sub['date'].max()}")
        out.append("")
        header = "| symbol | " + " | ".join(venues) + " |"
        sep = "|" + "---|" * (len(venues) + 1)
        out.append(header)
        out.append(sep)
        for sym in symbols:
            cells = []
            for v in venues:
                cell = sub[(sub["symbol"] == sym) & (sub["venue"] == v)]
                cells.append(f"{int(cell['rows'].sum()):,}" if not cell.empty else "·")
            out.append(f"| {sym} | " + " | ".join(cells) + " |")
        out.append("")
    return "\n".join(out)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    df = build_coverage()
    summary = _summary(df)
    (META_ROOT / "coverage.json").write_text(json.dumps({"summary": summary, "partitions": df.to_dict("records")},
                                                        indent=2, sort_keys=True, default=str))
    (META_ROOT / "coverage.md").write_text(_markdown_matrix(df) if not df.empty else "# Coverage matrix\n\n(no data)\n")
    print(f"coverage: {summary.get('partitions', 0)} partitions, "
          f"{summary.get('total_rows', 0):,} rows, {summary.get('total_bytes', 0)/1024/1024:.2f} MB")
    by_table: dict = defaultdict(int)
    for r in df.to_dict("records") if not df.empty else []:
        by_table[r["table_name"]] += r["rows"]
    for t, n in sorted(by_table.items()):
        print(f"  {t:<20} {n:>14,} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
